export const ARTICLE_CREATE_REQUEST = 'ARTICLE_CREATE_REQUEST';
export const ARTICLE_CREATE_SUCCESS = 'ARTICLE_CREATE_SUCCESS';
export const ARTICLE_CREATE_FAIL = 'ARTICLE_CREATE_FAIL';

export const ARTICLE_GET_REQUEST = 'ARTICLE_GET_REQUEST';
export const ARTICLE_GET_SUCCESS = 'ARTICLE_GET_SUCCESS';
export const ARTICLE_GET_FAIL = 'ARTICLE_GET_FAIL';