const GaleriImg = {
  1: require('./1 rmh org.webp'),
  2: require('./2 labonsa.webp'),
  3: require('./3 sd.webp'),
  4: require('./4 rani aca.webp'),
  5: require('./5 dermaga.webp'),
  6: require('./6 kelapa phon.webp'),
  7: require('./7 milkway.webp'),
  8: require('./8 pway.webp'),
  9: require('./9 mkanan.webp'),
  10: require('./10 sunsek.webp'),
  11: require('./11 lobster.webp'),
  12: require('./12 kalimalima.webp'),
  13: require('./13 bca2.webp'),
  14: require('./14 rumah.webp'),
  15: require('./15 moolo word.webp'),
  16: require('./16 kapal.webp'),
  17: require('./17 coklat.webp'),
  18: require('./18 org22.webp'),
  19: require('./19 mochi.webp'),
  20: require('./20 pemuda.webp'),
  21: require('./21 bakar2.webp'),
  22: require('./22 smp.webp'),
  23: require('./23 sapi.webp'),
  24: require('./24 kaeda.webp'),
  25: require('./25 mlm.webp'),
  26: require('./26 tk.webp'),
  27: require('./27 pnti.webp'),
};

export default GaleriImg;
